// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire_di

// InitializeApplication initializes the entire application with its dependencies
func InitializeApplication() (*Application, error) {
	// Initialize config
	config := NewConfig()
	
	// Initialize logger
	logger := NewLogger(config)
	
	// Initialize database connection
	databaseConnection, err := NewDatabaseConnection(config)
	if err != nil {
		return nil, err
	}
	
	// Initialize API client
	apiClient := NewAPIClient(config, logger)
	
	// Initialize repositories
	userRepository := NewUserRepository(databaseConnection, logger)
	messageRepository := NewMessageRepository(databaseConnection, logger)
	
	// Initialize notification service
	notificationService := NewNotificationService(apiClient, logger, config)
	
	// Initialize user service
	userService := NewUserService(userRepository, logger, notificationService)
	
	// Initialize message service
	messageService := NewMessageService(messageRepository, userRepository, logger, notificationService)
	
	// Initialize application with all dependencies
	application := NewApplication(userService, messageService, config, logger, databaseConnection)
	return application, nil
}
