# API Server Configuration
server:
  port: 8080

database:
  connectionString: "postgres://postgres:postgres@localhost:5432/eventstore?sslmode=disable"

messageBroker:
  connectionString: "amqp://guest:guest@localhost:5672/"
